MDS-396 | Updated documentation to add data quality/availability
hmrc/individuals-income-api pull request #109
Opened 2021-01-11 15:20 UTC by matthewharris1

Notice branch name doesn't have a - that's my bad.

2021-01-11 16:19 UTC, parkeradam requested changes

2021-01-11 16:19 UTC, parkeradam commented on resources/public/api/conf/2.0/application.raml
> + - title: Overview
Titles are wrong

2021-01-11 16:41 UTC, matthewharris1 commented on resources/public/api/conf/2.0/application.raml
> + - title: Overview
Good spot

2021-01-12 10:03 UTC, parkeradam approved these changes

2021-01-12 10:05 UTC, merged