Hods 260 : Documentation updates.
hmrc/individuals-income-api pull request #158
Opened 2021-06-29 11:10 UTC by parkeradam

2021-06-29 12:48 UTC, Luka-Abey requested changes
D in matchID needs to be lower case- should update in Lisa's doc too

2021-06-29 12:48 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-self-employments.md
> +        <td><p>The matchID is obtained from the Individuals Matching API. For example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430</p><p>fromTaxYear=2018-19</p><p>toTaxYear=2019-20</p></td>
matchId should have lower case D - looks like this is incorrect on Lisa's doc, so will need updating there too.

2021-06-29 12:48 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-source.md
> +            <p>The matchID is obtained from the Individuals Matching API. For example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430</p>
here as well

2021-06-29 12:48 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-summary.md
> +        <td><p>The matchID is obtained from the Individuals Matching API. For example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430</p><p>fromTaxYear=2018-19</p><p>toTaxYear=2019-20</p></td>
here too

2021-06-29 12:48 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-trusts.md
> +        <td><p>The matchID is obtained from the Individuals Matching API. For example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430</p><p>fromTaxYear=2018-19</p><p>toTaxYear=2019-20</p></td>
and here

2021-06-29 12:48 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-uk-properties.md
> +            <p>The matchID is obtained from the Individuals Matching API. For example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430</p>
and here

2021-06-29 12:48 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request.md
> +        <td><p>The matchID is obtained from the Individuals Matching API. For example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430</p><p>fromTaxYear=2018-19</p><p>toTaxYear=2019-20</p></td>
here

2021-06-29 12:48 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/root.md
> +      <td><p>The matchID is obtained from the Individuals Matching API. For example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430</p></td>
here

2021-06-29 12:48 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-request.md
> +        <td><p>The matchID is obtained from the Individuals Matching API. For example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430&gt;</p><p>fromDate=2018-01-01</p><p>toDate=2019-03-01</p></td>
here

2021-06-29 12:48 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-additional-information-request.md
> +            <p>The matchID is obtained from the Individuals Matching API. For example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430</p>
here

2021-06-29 12:48 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-dividends.md
> +        <td><p>The matchID is obtained from the Individuals Matching API. For example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430</p><p>fromTaxYear=2018-19</p><p>toTaxYear=2019-20</p></td>
here

2021-06-29 12:48 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-employments.md
> +        <td><p>The matchID is obtained from the Individuals Matching API. For example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430</p><p>fromTaxYear=2018-19</p><p>toTaxYear=2019-20</p></td>
here

2021-06-29 12:48 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-foreign.md
> +        <td><p>The matchID is obtained from the Individuals Matching API. For example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430</p><p>fromTaxYear=2018-19</p><p>toTaxYear=2019-20</p></td>
here

2021-06-29 12:48 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-further-details.md
> +            <p>The matchID is obtained from the Individuals Matching API. For example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430 </p>
.

2021-06-29 12:48 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-other.md
> +        <td><p>The matchID is obtained from the Individuals Matching API. For example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430</p><p>fromTaxYear=2018-19</p><p>toTaxYear=2019-20</p></td>
.

2021-06-29 12:48 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-pensions-benefits.md
> +        <td><p>The matchID is obtained from the Individuals Matching API. For example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430</p><p>fromTaxYear=2018-19</p><p>toTaxYear=2019-20</p></td>
.

2021-06-30 12:47 UTC, Luka-Abey commented
happy with matchId issue now, but need to have a proper review of the rest of the content..

2021-06-30 12:52 UTC, Luka-Abey approved these changes
approving the changes :)

2021-06-30 12:55 UTC, owen-opencast approved these changes

2021-07-01 15:45 UTC, Luka-Abey approved these changes
nice :)

2021-07-01 15:50 UTC, Luka-Abey requested changes
i didnt request changes

2021-07-01 15:50 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-further-details.md
> +            <p>For example, 2017-2018</p>
should these be colons instead of commas?
```suggestion
            <p>For example: 2017-2018</p>
```

2021-07-01 15:50 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-foreign.md
> +            <p>For example, 2017-2018</p>
```suggestion
            <p>For example: 2017-2018</p>
```

2021-07-01 15:50 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-employments.md
> +            <p>For example, 2017-2018</p>
```suggestion
            <p>For example: 2017-2018</p>
```

2021-07-01 15:50 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-additional-information-request.md
> +            <p>For example, 2017-2018</p>
```suggestion
            <p>For example: 2017-2018</p>
```

2021-07-01 15:50 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-dividends.md
> +            <p>For example, 2017-2018</p>
```suggestion
            <p>For example: 2017-2018</p>
```

2021-07-01 15:50 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-other.md
> +            <p>For example, 2017-2018</p>
```suggestion
            <p>For example: 2017-2018</p>
```

2021-07-01 15:50 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-partnerships.md
> +            <p>For example, fromTaxYear=2016-17 toTaxYear=2098-99</p>
```suggestion
            <p>For example: fromTaxYear=2016-17 toTaxYear=2098-99</p>
```

2021-07-01 15:50 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-partnerships.md
> +            <p>For example, fromTaxYear=2008-09</p>
```suggestion
            <p>For example: fromTaxYear=2008-09</p>
```

2021-07-01 15:50 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-pensions-benefits.md
> +            <p>For example, 2017-2018</p>
```suggestion
            <p>For example: 2017-2018</p>
```

2021-07-01 15:50 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-self-employments.md
> +            <p>For example, 2017-2018</p>
```suggestion
            <p>For example: 2017-2018</p>
```

2021-07-01 15:50 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-uk-properties.md
> +            <p>For example, 2017-2018</p>
```suggestion
            <p>For example: 2017-2018</p>
```

2021-07-01 15:50 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-trusts.md
> +            <p>For example, 2017-2018</p>
```suggestion
            <p>For example: 2017-2018</p>
```

2021-07-01 15:50 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-summary.md
> +            <p>For example, 2017-2018</p>
```suggestion
            <p>For example: 2017-2018</p>
```

2021-07-01 15:50 UTC, Luka-Abey commented on resources/public/api/conf/2.0/sandbox/income-sa-request-source.md
> +            <p>For example, 2017-2018</p>
```suggestion
            <p>For example: 2017-2018</p>
```

2021-07-01 15:56 UTC, Luka-Abey approved these changes

2021-07-02 10:12 UTC, merged