MDS-324 | Add stub V2 endpoints
hmrc/individuals-income-api pull request #85
Opened 2020-11-16 11:30 UTC by owen-opencast

2020-11-17 11:13 UTC, ajchilts requested changes
Great effort 👍 

Few comments.

2020-11-17 11:13 UTC, ajchilts commented on test/component/uk/gov/hmrc/individualsincomeapi/controllers/v2/IndividualIncomeSpec.scala
> +      And("DES will return employments for the NINO")
V2 will be on IF and not DES. Can we please remove the references to DES?

2020-11-17 11:13 UTC, ajchilts commented on test/component/uk/gov/hmrc/individualsincomeapi/controllers/v2/LiveSaIncomeControllerSpec.scala
> +    DesSAIncome(
V2 controller integrates with IF not DES. Can we remove the references to DES as they should not be needed for not yet implemented?

2020-11-17 11:13 UTC, ajchilts commented on test/component/uk/gov/hmrc/individualsincomeapi/controllers/v2/LiveSaIncomeControllerSpec.scala
> +      And("DES will return self-assessment data for the individual")
Please remove all references to DES.

2020-11-17 11:13 UTC, ajchilts commented on test/unit/uk/gov/hmrc/individualsincomeapi/controllers/v2/LiveRootControllerSpec.scala
> +//        mockAuthConnector.authorise(refEq(Enrolment("read:individuals-income")), refEq(EmptyRetrieval))(any(), any()))
Can we delete this commented out code?

2020-11-17 11:26 UTC, ajchilts requested changes

2020-11-17 11:26 UTC, ajchilts commented on test/component/uk/gov/hmrc/individualsincomeapi/VersioningSpec.scala
> +      Then("The response status should be 200")
Test specifies 200 then we expect INTERNAL_SERVER_ERROR?

Please correct all occurrences.

2020-11-20 12:57 UTC, owen-opencast commented on conf/app_version_P2.routes
> +GET        /sa/source                       uk.gov.hmrc.individualsincomeapi.controllers.v2.LiveSaIncomeController.saIncomeSource(matchId: java.util.UUID, taxYearInterval: uk.gov.hmrc.individualsinco
Added further-details now, not sure why it's not appearing here? Can someone pull the branch and check?

2020-11-20 12:57 UTC, owen-opencast commented on app/uk/gov/hmrc/individualsincomeapi/controllers/v2/SaIncomeController.scala
> +}
See above

2020-11-20 12:57 UTC, owen-opencast commented on conf/sandbox_version_P2.routes
> +GET        /sa/source                       uk.gov.hmrc.individualsincomeapi.controllers.v2.SandboxSaIncomeController.saIncomeSource(matchId: java.util.UUID, taxYearInterval: uk.gov.hmrc.individualsi
See above

2020-11-23 10:11 UTC, ajchilts approved these changes
LGTM 👍

2020-11-23 15:17 UTC, mostafasina commented
Regression tests in local dev passed.

2020-11-23 15:17 UTC, merged