MDS-374 | SA API Documentation
hmrc/individuals-income-api pull request #90
Opened 2020-12-08 13:50 UTC by ajchilts

https://docs.google.com/document/d/1Ch-i9I1d-pqGpjvV7UmMPwhjJjViocpBWAwQW7JdYq8/edit#

2020-12-09 16:00 UTC, parkeradam requested changes
General comment as well, are all the fields required as users may not get it back if they dont have the right scope.

2020-12-10 08:46 UTC, ajchilts commented on resources/public/api/conf/P2.0/examples/income-sa-source-response.json
> +            }
It's meant to be missing. It's an example where it's not present.

2020-12-10 08:46 UTC, ajchilts commented on resources/public/api/conf/P2.0/application.raml
> +      (annotations.scope): "The scopes you have been assigned"
Done

2020-12-10 08:47 UTC, ajchilts commented on resources/public/api/conf/P2.0/examples/income-sa-further-details-response.json
> +            "busStartDate": "2018-02-28",
I was trying to keep the response inline with the other SA responses in terms of the structure as this makes more sense to the OGDs than the IF structure. I.e. it follows the schema structure of the other endpoints.

2020-12-10 08:48 UTC, ajchilts commented on resources/public/api/conf/P2.0/examples/income-sa-source-response.json
> +              "postalCode": "TF22 3BC"
It's postal code for HO and as we will be bringing HO into this solution at some point we will adopt the HO name over the IF name.

2020-12-10 09:20 UTC, ajchilts commented on resources/public/api/conf/P2.0/examples/income-response.json
> +        "weekPayNumber": 46
True. Greyed out. My bad. Removed.

2020-12-10 09:24 UTC, ajchilts commented on resources/public/api/conf/P2.0/schemas/income-sa-source-response.json
> +                      "type": "object",
Done

2020-12-10 09:26 UTC, ajchilts commented on resources/public/api/conf/P2.0/examples/root.json
> +      "href": "/individuals/income/paye?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430&startYear=2018-19&endYear=2019-20",
Its not in any of the V1 schemas...

2020-12-10 09:28 UTC, ajchilts commented on resources/public/api/conf/P2.0/examples/root.json
> +      "href": "/individuals/income/paye?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430&startYear=2018-19&endYear=2019-20",
Added for V2

2020-12-10 09:29 UTC, ajchilts commented on resources/public/api/conf/P2.0/examples/income-sa-source-response.json
> +			  "addressEffectiveDate": "2017-01-31"
Removed. Captain cut and paste. Well spotted.

2020-12-10 09:30 UTC, ajchilts commented on resources/public/api/conf/P2.0/examples/income-sa-source-response.json
> +            }
Added anyway as it could cause confusion. Just copied the V1 approach.

2020-12-10 10:44 UTC, parkeradam commented on resources/public/api/conf/P2.0/examples/income-sa-further-details-response.json
> +            "busStartDate": "2018-02-28",
Ok that seems fair.

2020-12-10 10:48 UTC, parkeradam approved these changes

2020-12-10 10:51 UTC, merged